import Navbar from "@app/components/Navbar";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@app/providers";
import Footer from "@app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
